Code & Features Update

diff --git a/frobulator b/frobulator
--- a/frobulator
+++ b/frobulator
@@ -2007,7 +2007,7 @@ frobulator.complete () {
 
 	# Number	Meaning			Example			Comments
 	#   0		
-	#   1		Catchall for general errors	let "var1 = 1/0"	Miscellaneous errors, such as "divide by zero" and other impermissible operations
+	#   1		Catchall for general errors 	 let "var1 = 1/0"	Miscellaneous errors, such as "divide by zero" and other impermissible operations
 	#   2		Misuse of shell builtins (according to Bash documentation)	empty_function() {}	Missing keyword or command, or permission problem (and diff return code on a failed binary file comparison).
 	# 126		Command invoked cannot execute	/dev/null	Permission problem or command is not an executable
 	# 127		"command not found"	illegal_command	Possible problem with $PATH or a typo
@@ -2016,22 +2016,26 @@ frobulator.complete () {
 	# 130		Script terminated by Control-C	Ctl-C	Control-C is fatal error signal 2, (130 = 128 + 2, see above)
 	# 255*		Exit status out of range	exit -1	exit takes only integer args in the range 0 - 255
 
+	# catch process exit status of last command
+	
+	PES=${?}
+	
 	command="${1}"
 
 	execute="${2}"
 
-	if [[ ${?} = 0 ]]
+	if [[ ! "${PES}" = 0 ]]
 	then
-		frobulator.cpt "Complete" "[ ${command} ]"
-		echo
-		
-		"${execute}"
-		
-	else
 		frobulator.err "Incomplete - errors encountered" "[ ${command} ]"
 		echo
 		
 		frobulator.wrn "Consult log for process details" "[ ${log} ]"
+		echo
+		
+		exit 1
+		
+	else
+		frobulator.cpt "Complete" "[ ${command} ]"
 		echo
 	fi
 
