Code & Features Update

diff --git a/frobulator b/frobulator
--- a/frobulator
+++ b/frobulator
@@ -1405,7 +1405,7 @@ frobulator.hold () {
 	list=()
 }
 
-# release /////////////////////////////////////////////////////////////////////#
+# release //////////////////////////////////////////////////////////////////////
 
 frobulator.release () {
 	export DEBIAN_FRONTEND=noninteractive
@@ -1816,7 +1816,51 @@ frobulator.require () {
 	done
 }
 
-# superuser ////////////////////////////////////////////////////////////////////
+# assess ///////////////////////////////////////////////////////////////////////
+
+frobulator.assess () {
+	if [[ -n "${#list[@]}" ]]
+	then
+		# ${1} - array
+
+		list=(${@:1})
+	else
+		command="${1}"
+
+		list=()
+
+		list+=("${command}")
+	fi
+
+	if [[ $(id -u -n) = "root" ]]
+	then
+		frobulator.require ${list[@]}
+
+		frobulator.msg "Requirements installed" "[ ${script} ]"
+		echo
+
+		frobulator.inf "Run '${script}' as 'user' to proceed."
+		echo
+
+		exit
+	else
+		for requirement in ${list[@]}
+		do
+			if [[ -z $(command -v "${requirement}") ]]
+			then
+				frobulator.err "Missing" "[ '${requirement}' ]"
+				echo
+
+				frobulator.wrn "Launch '${script}' as 'root' to install requirements."
+				echo
+
+				exit 1
+			fi
+		done
+	fi
+}
+
+# escalate /////////////////////////////////////////////////////////////////////
 
 frobulator.escalate () {
 	if [[ $(id -u -n) = "root" ]]
