Code & Features Update

diff --git a/frobulator b/frobulator
--- a/frobulator
+++ b/frobulator
@@ -2,7 +2,97 @@
 
 # dependencies /////////////////////////////////////////////////////////////////
 
+if [[ $(id -u -n) = "root" ]]
+then
+	SUDO_HOME=/root
+
+	USER="${SUDO_USER:-root}"
+
+	if [ "${USER}" = "root" ]
+	then
+		HOME=/root
+	else
+		HOME="/home/${USER}"
+	fi
+fi
+
+echo
+
+echo "[  -  ] Checking..."
+echo
+
+if [[ -z $(command -v curl) ]]
+then
+	if [[ -n $(command -v apt-get) ]]
+	then
+		apt-get -q -q update > /dev/null 2>&1
+		apt-get -q -q install -y curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v dnf) ]]
+	then
+		dnf -q install -y curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v yum) ]]
+	then
+		yum -q install -y curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v apk) ]]
+	then
+		apk add --quiet curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v pacman) ]]
+	then
+		pacman -S -y --noconfirm --noprogressbar curl > /dev/null 2>&1
+
+	elif [[ -n $(command -v zypper) ]]
+	then
+		zypper --quiet --non-interactive install curl > /dev/null 2>&1
+	fi
+fi
+
+if [[ -z $(command -v curl) ]]
+then
+	echo "[  !  ] Unable to install or binary not found /////////////////////// [ 'curl' ]"
+	echo
+
+	exit 1
+fi
+
+mkdir -p "${HOME}"/.local/bin
+
+frobulator="${HOME}"/.local/bin/frobulator
+
+version_online=$(	curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
+
+version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)
+
+version_local="${version_local:-01-01-1970}"
+
+date_online="${version_online:6:4}${version_online:0:2}${version_online:3:2}"
+
+date_local="${version_local:6:4}${version_local:0:2}${version_local:3:2}"
+
+if [ ! -f "${frobulator}" ] || [[ "${date_online}" > "${date_local}" ]]
+then
+	curl -s -L get.frbltr.app > "${frobulator}"
+
+	chmod +x "${frobulator}"
+fi
+
+echo "[  >  ] Implementing..."
+echo
+
+source "${frobulator}"
+
+# superuser ////////////////////////////////////////////////////////////////////
+
+export self_arguments="${@}"
+
+# frobulator.escalate
+
 # script ///////////////////////////////////////////////////////////////////////
+
+script="$(basename -- ${BASH_SOURCE[0]})"
 
 # version //////////////////////////////////////////////////////////////////////
 
@@ -107,7 +197,7 @@ fi
 
 # provide system shell
 
-if [ -z "${SHELL}" ]
+if [ ! -f "${frobulator}" ] || [[ "${date_online}" > "${date_local}" ]]-z "${SHELL}" ]
 then
 	if [[ $(command -v /bin/bash) ]]
 	then
@@ -127,14 +217,14 @@ terminal_columns=80
 
 self="${0}"
 
-if [ -z "${script}" ]
+if [ ! -f "${frobulator}" ] || [[ "${date_online}" > "${date_local}" ]]-z "${script}" ]
 then
 	script="${self}"
 fi
 
 # provide null sink for argument / error / output silencing
 
-if [ -e /dev/null ]
+if [ ! -f "${frobulator}" ] || [[ "${date_online}" > "${date_local}" ]]-e /dev/null ]
 then
 	sink="/dev/null"
 fi
@@ -465,7 +555,7 @@ colors_selection=(
 	teal="30"
 )
 
-if [ -z "$(command -v tput)" ]
+if [ ! -f "${frobulator}" ] || [[ "${date_online}" > "${date_local}" ]]-z "$(command -v tput)" ]
 then
 	# handle color digit length for ansi fallback method
 
