Code & Features Update

diff --git a/frobulator b/frobulator
--- a/frobulator
+++ b/frobulator
@@ -2034,7 +2034,6 @@ frobulator.complete () {
 	PES=${?}
 	
 	command="${1}"
-	log="${2}"
 	
 	if [[ ! "${PES}" = 0 ]]
 	then
@@ -2048,6 +2047,31 @@ frobulator.complete () {
 		echo
 
 		return 0
+
+	fi
+
+}
+
+frobulator.continue () {
+
+	# catch process exit status of last command
+
+	PES=${?}
+
+	command="${1}"
+
+	if [[ ! "${PES}" = 0 ]]
+	then
+		frobulator.stp "Aborting${marker_elp}"
+		echo
+
+		exit 1
+
+	else
+		frobulator.fwd "Continuing${marker_elp}"
+		echo
+
+		exit 0
 
 	fi
 
